---
# Raspberry Pi configuration.
drupal_pi_processor_count: 4
pi_install_php_from_source: false

# Drupal configuration.
drupal_site_name: "Drupal Pi"
drupal_site_canonical_uri: "www.drupalpi.dev"
drupal_site_redirect_uri: "drupalpi.dev"
drupal_core_path: /var/www/drupal
drupal_account_name: admin
drupal_account_pass: admin

# Nginx configuration.
nginx_worker_processes: "{{ drupal_pi_processor_count }}"
nginx_worker_connections: "512"
nginx_client_max_body_size: "64m"
nginx_keepalive_timeout: "65"
nginx_remove_default_vhost: true
nginx_vhosts: []
nginx_access_log: "off"

# MySQL configuration.
mysql_key_buffer_size: "16M"
mysql_max_allowed_packet: "64M"
mysql_table_open_cache: "256"
mysql_sort_buffer_size: "1M"
mysql_read_buffer_size: "1M"
mysql_read_rnd_buffer_size: "2M"
mysql_myisam_sort_buffer_size: "16M"
mysql_thread_cache_size: "25"
mysql_query_cache_size: "16M"
mysql_innodb_buffer_pool_size: "64M"
mysql_innodb_log_file_size: "8M"
mysql_innodb_log_buffer_size: "4M"
mysql_innodb_flush_log_at_trx_commit: "2"
mysql_root_password: supersecure
mysql_users:
  - name: drupal
    host: "%"
    password: supersecure
    priv: "drupal.*:ALL"

mysql_databases:
  - name: drupal
    collation: utf8_general_ci
    encoding: utf8
    replicate: 0

# PHP configuration.
php_webserver_daemon: "nginx"
php_enable_php_fpm: true
php_memory_limit: "128M"
php_max_execution_time: "240"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "128"
php_fpm_listen: "127.0.0.1:9000"
php_fpm_listen_allowed_clients: "127.0.0.1"
php_fpm_pm_max_children: 7
php_fpm_pm_start_servers: 4
php_fpm_pm_min_spare_servers: 2
php_fpm_pm_max_spare_servers: 4
php_conf_paths:
  - /etc/php5/fpm
  - /etc/php5/cli
php_extension_conf_paths:
  - /etc/php5/fpm/conf.d
  - /etc/php5/cli/conf.d
# Uncomment for Raspbian on Raspberry Pi.
php_source_install_gmp_path: "/usr/include/arm-linux-gnueabihf/gmp.h"
# Uncomment for ODROBIAN on ODROID-C2.
# php_source_install_gmp_path: "/usr/include/aarch64-linux-gnu/gmp.h"

# Drush configuration.
drush_version: "master"
drush_makefile_path: "{{ playbook_dir }}/drupal.make.yml"

# Security configuration.
security_sudoers_passwordless: ['pi']
firewall_allowed_tcp_ports:
  - 22
  - 80
